// This file is auto-generated by Payload CMS.
// Do not edit this file manually.
// It will be regenerated when you run `payload generate:importmap`

import type { ImportMap } from 'payload'

export const importMap: ImportMap = {}
